export default [
  'focus',
  'blur',
  'setMode',
  'exitCurrentMode',
  'restoreEditorDOM',
  'setRenderGuard',
  'removeRenderGuard',
  'setClipboard',
  'getClipboard',
  'getEditorKey',
  'update',
  'onDragEnter',
  'onDragLeave',
];
